dataset_params:
  im_path: 'data/imagenet'
  im_channels : 3
  im_size : 256
  name: 'IMAGENET'
  val_num_samples : 5000 
  latent_channels : 24
  num_classes: 1000

diffusion_params:
  num_timesteps : 1000

train_params:
  seed : 661
  alpha : 0.5
  task_name: 'LDM_IMG_ND_24x64x64'
  num_timesteps : 1000
  denoising_timesteps : 1000
  num_warmup_steps: 5000
  batch_size: 160
  val_batch_size : 100
  drop_p: 5e-5
  max_steps : 600000
  lr: 0.0001
  acc_steps : 2
  nd : True
  log_steps : 500
  fid_steps : 20000
  fid_sample_steps : 50
  ldm_ckpt_name: 'ddpm_ckpt.pth'
  snr_gamma: 5.0
  cond_drop_prob: 0.1
  guidance_scale: 4.0
