dataset_params:
  im_path: 'data/FFHQ'
  im_channels : 3
  im_size : 256
  name: 'FFHQ'
  val_num_samples : 100 
  latent_channels : 24

diffusion_params:
  num_timesteps : 1000

train_params:
  seed : 661
  alpha : 0.5
  task_name: 'TEST'
  num_timesteps : 1000
  denoising_timesteps : 1000
  num_warmup_steps: 5000
  batch_size: 25
  val_batch_size : 25
  drop_p: 5e-5
  max_steps : 250000
  lr: 0.0001
  acc_steps : 4
  nd : True
  log_steps : 10
  fid_steps : 10
  ldm_ckpt_name: 'ddpm_ckpt.pth'
  snr_gamma: 5.0
